default[:db_mongodb][:data_dir] = "/var/mongodb/data"
default[:db_mongodb][:conf_file] = "/etc/mongod.conf"
default[:db_mongodb][:log_file] = "/var/log/mongod.log"
default[:db_mongodb][:tarball] = "mongodb-linux-i686-1.8.1.tgz"
default[:db_mongodb][:content_dir] = "/tmp/mongodb-linux-i686-1.8.1"
